Greeting.create(message: 'Hello everyone.')
Greeting.create(message: 'It\'s nice to see you.')
Greeting.create(message: 'Welcome.')
Greeting.create(message: 'Hi!!!')
Greeting.create(message: 'Guten Tag.')
